# Generated by Django 4.2.2 on 2023-06-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('rut', models.IntegerField(verbose_name='Rut')),
                ('direccion', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
            ],
        ),
    ]
