# Generated by Django 4.2.2 on 2023-06-29 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_ciudad_alter_usuario_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_Categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id categoría')),
                ('nombreCategoria', models.CharField(max_length=150, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del producto')),
                ('producto', models.CharField(max_length=200, verbose_name='nombre del producto')),
                ('detalles', models.CharField(blank=True, max_length=300, null=True, verbose_name='detalles del producto')),
                ('imagen', models.ImageField(default='nn.jpg', upload_to='images/', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
